# ============================================================================
# Agentic OS - ラベルベース状態機械定義（日本語版）
# ============================================================================
#
# ラベルはオペレーティングシステムの状態管理機構として機能します。
# すべての自動化は、Issue/PRの状態を判断するためにラベルを確認する必要があります。
#
# 状態フロー:
#   📥 保留中 → 🔍 分析中 → 🏗️ 実装中 → 👀 レビュー中 → ✅ 完了
#
# 憲法要件:
#   「すべてはIssueから始まる。ラベルが状態を定義する。」
#
# ============================================================================

# ============================================================================
# 1. 状態ラベル（ライフサイクル管理）
# ============================================================================

- name: "📥 状態:保留中"
  color: "E4E4E4"
  description: "Issue作成済み、トリアージ待ち"
  aliases: ["pending", "triage", "state:pending"]

- name: "🔍 状態:分析中"
  color: "0E8A16"
  description: "CoordinatorAgentが依存関係と複雑性を分析中"
  aliases: ["analyzing", "analysis", "state:analyzing"]

- name: "🏗️ 状態:実装中"
  color: "1D76DB"
  description: "SpecialistAgentが実装作業中"
  aliases: ["implementing", "in-progress", "wip", "state:implementing"]

- name: "👀 状態:レビュー中"
  color: "FBCA04"
  description: "ReviewAgentが品質チェック実施中"
  aliases: ["reviewing", "review", "qa", "state:reviewing"]

- name: "✅ 状態:完了"
  color: "2EA44F"
  description: "正常完了、mainにマージ済み"
  aliases: ["done", "completed", "merged", "state:done"]

- name: "🔴 状態:ブロック中"
  color: "D73A4A"
  description: "ブロック中 - Guardian介入必要"
  aliases: ["blocked", "stuck", "state:blocked"]

- name: "🛑 状態:失敗"
  color: "B60205"
  description: "実行失敗 - エラー発生"
  aliases: ["failed", "error", "state:failed"]

- name: "⏸️ 状態:一時停止"
  color: "D4C5F9"
  description: "一時停止 - 依存関係または承認待ち"
  aliases: ["paused", "waiting", "state:paused"]

# ============================================================================
# 2. Agent割り当てラベル
# ============================================================================

- name: "🤖 担当:Coordinator"
  color: "FF79C6"
  description: "CoordinatorAgentに割り当て"
  aliases: ["coordinator", "agent:coordinator"]

- name: "🤖 担当:CodeGen"
  color: "00D9FF"
  description: "CodeGenAgentに割り当て"
  aliases: ["codegen", "agent:codegen"]

- name: "🤖 担当:Review"
  color: "00FF88"
  description: "ReviewAgentに割り当て"
  aliases: ["review", "agent:review"]

- name: "🤖 担当:Issue"
  color: "8B88FF"
  description: "IssueAgentに割り当て"
  aliases: ["issue-agent", "agent:issue"]

- name: "🤖 担当:PR"
  color: "FF79C6"
  description: "PRAgentに割り当て"
  aliases: ["pr-agent", "agent:pr"]

- name: "🤖 担当:Deploy"
  color: "FF4444"
  description: "DeploymentAgentに割り当て"
  aliases: ["deployment", "agent:deployment"]

# ============================================================================
# 3. 優先度ラベル
# ============================================================================

- name: "🔥 優先度:P0-緊急"
  color: "B60205"
  description: "緊急 - セキュリティ、本番障害、データ損失"
  aliases: ["critical", "p0", "urgent", "priority:P0-Critical"]

- name: "⚠️ 優先度:P1-高"
  color: "D93F0B"
  description: "高 - 主要機能、重要なバグ"
  aliases: ["high", "p1", "priority:P1-High"]

- name: "📊 優先度:P2-中"
  color: "FBCA04"
  description: "中 - 標準的な機能またはバグ"
  aliases: ["medium", "p2", "priority:P2-Medium"]

- name: "📝 優先度:P3-低"
  color: "0E8A16"
  description: "低 - あると良い、軽微な改善"
  aliases: ["low", "p3", "priority:P3-Low"]

# ============================================================================
# 4. 種別ラベル（Issue分類）
# ============================================================================

- name: "✨ 種別:機能追加"
  color: "00D9FF"
  description: "新機能または機能強化"
  aliases: ["feature", "enhancement", "type:feature"]

- name: "🐛 種別:バグ修正"
  color: "D73A4A"
  description: "バグ修正"
  aliases: ["bug", "defect", "type:bug"]

- name: "📚 種別:ドキュメント"
  color: "0075CA"
  description: "ドキュメント改善"
  aliases: ["docs", "documentation", "type:docs"]

- name: "🔧 種別:リファクタリング"
  color: "FBCA04"
  description: "コードリファクタリング"
  aliases: ["refactor", "type:refactor"]

- name: "🧪 種別:テスト"
  color: "00FF88"
  description: "テスト追加または改善"
  aliases: ["test", "testing", "type:test"]

- name: "🏗️ 種別:アーキテクチャ"
  color: "8B88FF"
  description: "アーキテクチャ設計またはシステムレベル変更"
  aliases: ["architecture", "design", "type:architecture"]

- name: "🚀 種別:デプロイ"
  color: "FF4444"
  description: "デプロイまたはインフラ"
  aliases: ["deployment", "infra", "type:deployment"]

# ============================================================================
# 5. 深刻度ラベル（エスカレーション）
# ============================================================================

- name: "🚨 深刻度:Sev.1-緊急"
  color: "B60205"
  description: "緊急 - 即座にGuardianエスカレーション必要"
  aliases: ["sev1", "critical-severity", "severity:Sev.1-Critical"]

- name: "⚠️ 深刻度:Sev.2-高"
  color: "D93F0B"
  description: "高 - TechLead/CISOエスカレーション推奨"
  aliases: ["sev2", "high-severity", "severity:Sev.2-High"]

- name: "📊 深刻度:Sev.3-中"
  color: "FBCA04"
  description: "中 - 注視が必要"
  aliases: ["sev3", "medium-severity", "severity:Sev.3-Medium"]

- name: "📝 深刻度:Sev.4-低"
  color: "0E8A16"
  description: "低 - 通常対応"
  aliases: ["sev4", "low-severity", "severity:Sev.4-Low"]

# ============================================================================
# 6. フェーズラベル（プロジェクト管理）
# ============================================================================

- name: "🎯 フェーズ:計画"
  color: "D4C5F9"
  description: "計画フェーズ"
  aliases: ["planning", "phase:planning"]

- name: "🏗️ フェーズ:実装"
  color: "1D76DB"
  description: "実装フェーズ"
  aliases: ["implementation", "phase:implementation"]

- name: "🧪 フェーズ:テスト"
  color: "00FF88"
  description: "テストフェーズ"
  aliases: ["testing", "phase:testing"]

- name: "🚀 フェーズ:デプロイ"
  color: "FF4444"
  description: "デプロイフェーズ"
  aliases: ["deployment-phase", "phase:deployment"]

- name: "📊 フェーズ:監視"
  color: "0E8A16"
  description: "監視フェーズ"
  aliases: ["monitoring", "phase:monitoring"]

# ============================================================================
# 7. 特殊操作ラベル
# ============================================================================

- name: "🔐 セキュリティ"
  color: "B60205"
  description: "セキュリティ関連Issue - CISOエスカレーション"
  aliases: ["security", "vuln"]

- name: "💰 コスト監視"
  color: "FBCA04"
  description: "高コスト操作 - 予算監視"
  aliases: ["cost", "expensive", "cost-watch"]

- name: "🔄 依存関係あり"
  color: "8B88FF"
  description: "依存関係あり - 先に解決必要"
  aliases: ["deps", "dependency", "dependencies"]

- name: "🎓 学習タスク"
  color: "7057FF"
  description: "学習タスク - 時間がかかる可能性"
  aliases: ["learning", "research"]

- name: "🔬 実験的"
  color: "D4C5F9"
  description: "実験的 - 失敗する可能性"
  aliases: ["experiment", "spike"]

- name: "🚫 修正なし"
  color: "E4E4E4"
  description: "修正しない - クローズ"
  aliases: ["wontfix", "declined"]

- name: "🔁 重複"
  color: "CFD3D7"
  description: "別Issueと重複"
  aliases: ["duplicate"]

# ============================================================================
# 8. 自動トリガーラベル
# ============================================================================

- name: "🤖 トリガー:Agent実行"
  color: "FF79C6"
  description: "トリガー: 自律Agentを実行"
  aliases: ["agent-execute", "execute", "trigger:agent-execute"]

- name: "📊 トリガー:レポート生成"
  color: "0E8A16"
  description: "トリガー: 週次レポート生成"
  aliases: ["report", "generate-report", "trigger:generate-report"]

- name: "🚀 トリガー:ステージング"
  color: "FBCA04"
  description: "トリガー: ステージング環境へデプロイ"
  aliases: ["deploy-staging", "trigger:deploy-staging"]

- name: "🚀 トリガー:本番環境"
  color: "D73A4A"
  description: "トリガー: 本番環境へデプロイ（Guardian承認必要）"
  aliases: ["deploy-production", "trigger:deploy-production"]

# ============================================================================
# 9. 品質ラベル
# ============================================================================

- name: "⭐ 品質:優秀"
  color: "2EA44F"
  description: "品質スコア: 90-100 (優秀)"
  aliases: ["excellent", "quality:excellent"]

- name: "✅ 品質:良好"
  color: "00FF88"
  description: "品質スコア: 80-89 (良好)"
  aliases: ["good", "quality:good"]

- name: "⚠️ 品質:要改善"
  color: "FBCA04"
  description: "品質スコア: 60-79 (改善必要)"
  aliases: ["needs-improvement", "quality:needs-improvement"]

- name: "🔴 品質:不良"
  color: "D73A4A"
  description: "品質スコア: <60 (不良 - 作り直し必要)"
  aliases: ["poor", "quality:poor"]

# ============================================================================
# 10. コミュニティラベル
# ============================================================================

- name: "👋 初心者向け"
  color: "7057FF"
  description: "初心者に適したタスク"
  aliases: ["good-first-issue", "beginner"]

- name: "🙏 ヘルプ募集"
  color: "0E8A16"
  description: "コミュニティのヘルプ募集"
  aliases: ["help-wanted"]

- name: "❓ 質問"
  color: "D4C5F9"
  description: "質問またはディスカッション"
  aliases: ["question"]

- name: "💬 議論"
  color: "D4C5F9"
  description: "オープンディスカッション"
  aliases: ["discussion"]

# ============================================================================
# 状態遷移ルール
# ============================================================================
#
# 1. 保留中 → 分析中
#    - トリガー: CoordinatorAgent割り当て
#    - アクション: 依存関係、複雑性を分析
#
# 2. 分析中 → 実装中
#    - トリガー: 分析完了、Specialist割り当て
#    - アクション: CodeGenAgent/PRAgentが作業開始
#
# 3. 実装中 → レビュー中
#    - トリガー: PR作成
#    - アクション: ReviewAgentが品質チェック開始
#
# 4. レビュー中 → 完了
#    - トリガー: 品質スコア ≥ 80、PRマージ
#    - アクション: Issueクローズ、メトリクス更新
#
# 5. 任意 → ブロック中
#    - トリガー: エラー、依存関係不足、承認必要
#    - アクション: Guardianにエスカレート
#
# 6. 任意 → 失敗
#    - トリガー: 回復不可能なエラー
#    - アクション: エラーログ、エスカレート
#
# 7. ブロック中/失敗 → 分析中
#    - トリガー: Guardian解決、再試行準備完了
#    - アクション: 分析から再開
#
# ============================================================================
