name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug] "
labels: ["🐛 type:bug", "📥 state:pending"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🐛 Bug Report
        Thank you for reporting a bug! Please provide as much detail as possible.

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: What is the bug? What happened?
      placeholder: A clear and concise description of the bug...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what should have happened...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this bug?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: What environment are you using?
      placeholder: |
        - OS: [e.g., macOS 14.0, Ubuntu 22.04]
        - Node.js: [e.g., v20.10.0]
        - Browser: [e.g., Chrome 120, Safari 17]
        - Package version: [e.g., 0.3.3]
      value: |
        - OS:
        - Node.js:
        - Browser:
        - Package version:
    validations:
      required: true

  - type: textarea
    id: error-logs
    attributes:
      label: Error Logs
      description: Include any error messages or logs
      placeholder: Paste error logs here...
      render: shell
    validations:
      required: false

  - type: textarea
    id: dependencies
    attributes:
      label: 🔗 Dependencies
      description: |
        Does this bug relate to other issues?
        Use the following format:
        - `Depends on #XXX` - This bug fix depends on another issue
        - `Blocks #YYY` - This bug blocks other work
        - `Related to #ZZZ` - This bug is related to another issue
      placeholder: |
        Depends on #42
        Blocks #56
        Related to #53
      value: |
        <!-- Dependencies (optional) -->
    validations:
      required: false

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - 🚨 Sev.1 - Critical (System down)
        - 🔥 Sev.2 - High (Major feature broken)
        - ⚠️ Sev.3 - Medium (Minor issue)
        - 📝 Sev.4 - Low (Cosmetic)
      default: 2
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is this fix?
      options:
        - 🔥 P0 - Critical (Fix immediately)
        - ⚡ P1 - High (Fix soon)
        - 📌 P2 - Medium (Normal)
        - 📝 P3 - Low (Can wait)
      default: 2
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Add screenshots if applicable
      placeholder: Drag and drop images here...
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem
      placeholder: Any additional information...
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched for similar bug reports
          required: true
        - label: I have included steps to reproduce
          required: true
        - label: I have included environment information
          required: true
