blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://shunsukehayashi.github.io/Miyabi/
    about: Read the full documentation and guides
  - name: 💬 Discussions
    url: https://github.com/ShunsukeHayashi/Miyabi/discussions
    about: Ask questions and discuss with the community
  - name: 🌐 Dashboard
    url: https://shunsukehayashi.github.io/Miyabi/
    about: View the live Miyabi dashboard
  - name: 📦 NPM Package
    url: https://www.npmjs.com/package/miyabi
    about: View the Miyabi CLI package on NPM
