name: Snapshot Testing

on:
  pull_request:
    paths:
      - 'agents/**/*.ts'
      - 'tests/**/*.test.ts'
      - 'tests/__snapshots__/**'
  push:
    branches: [main, develop]
    paths:
      - 'agents/**/*.ts'
      - 'tests/**/*.test.ts'
      - 'tests/__snapshots__/**'

jobs:
  snapshot-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run snapshot tests
        run: npm run test -- --run --reporter=verbose tests/ReviewAgent.test.ts
        continue-on-error: true
        id: snapshot_test

      - name: Check for snapshot changes
        id: snapshot_diff
        run: |
          if git diff --exit-code tests/**/__snapshots__; then
            echo "status=no-changes" >> $GITHUB_OUTPUT
            echo "✅ No snapshot changes detected"
          else
            echo "status=has-changes" >> $GITHUB_OUTPUT
            echo "❌ Snapshot changes detected - Review required"
            echo "## Snapshot Diff" >> $GITHUB_STEP_SUMMARY
            echo '```diff' >> $GITHUB_STEP_SUMMARY
            git diff tests/**/__snapshots__ >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
          fi

      - name: Upload snapshot diff
        if: steps.snapshot_diff.outputs.status == 'has-changes'
        uses: actions/upload-artifact@v4
        with:
          name: snapshot-diff
          path: tests/**/__snapshots__
          retention-days: 7

      - name: Comment on PR with snapshot changes
        if: steps.snapshot_diff.outputs.status == 'has-changes' && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const { execSync } = require('child_process');

            const diff = execSync('git diff tests/**/__snapshots__', { encoding: 'utf8' });

            const comment = `## ⚠️ Snapshot Changes Detected

            Snapshot changes were detected in this PR. Please review carefully:

            <details>
            <summary>View Snapshot Diff</summary>

            \`\`\`diff
            ${diff}
            \`\`\`

            </details>

            ### Next Steps:

            1. **If changes are expected**: Update snapshots with \`npm run test -- -u\`
            2. **If changes are unexpected**: Investigate why output changed
            3. **If unsure**: Ask for review from maintainers

            ---
            🤖 Generated by Snapshot Testing Workflow
            `;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });

      - name: Fail if snapshots changed without update
        if: steps.snapshot_diff.outputs.status == 'has-changes'
        run: |
          echo "::error::Snapshot changes detected but not committed. Run 'npm run test -- -u' to update snapshots."
          exit 1

      - name: Report test results
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const status = '${{ steps.snapshot_test.outcome }}';
            const diffStatus = '${{ steps.snapshot_diff.outputs.status }}';

            let summary = '## 📸 Snapshot Test Results\n\n';

            if (status === 'success' && diffStatus === 'no-changes') {
              summary += '✅ **All snapshot tests passed** - No changes detected\n';
            } else if (status === 'success' && diffStatus === 'has-changes') {
              summary += '⚠️ **Tests passed but snapshots changed** - Review required\n';
            } else {
              summary += '❌ **Tests failed** - Please fix issues\n';
            }

            core.summary.addRaw(summary).write();
